// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/ova-food-api/ova-food-api.proto

package ova_food_api

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FoodType int32

const (
	FoodType_Unknown FoodType = 0
	FoodType_Drinks  FoodType = 1
	FoodType_Foods   FoodType = 2
)

var FoodType_name = map[int32]string{
	0: "Unknown",
	1: "Drinks",
	2: "Foods",
}

var FoodType_value = map[string]int32{
	"Unknown": 0,
	"Drinks":  1,
	"Foods":   2,
}

func (x FoodType) String() string {
	return proto.EnumName(FoodType_name, int32(x))
}

func (FoodType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{0}
}

type CreationFood struct {
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FoodT                FoodType `protobuf:"varint,3,opt,name=food_t,json=foodT,proto3,enum=ova.food.api.FoodType" json:"food_t,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PortionSize          float32  `protobuf:"fixed32,5,opt,name=portion_size,json=portionSize,proto3" json:"portion_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreationFood) Reset()         { *m = CreationFood{} }
func (m *CreationFood) String() string { return proto.CompactTextString(m) }
func (*CreationFood) ProtoMessage()    {}
func (*CreationFood) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{0}
}

func (m *CreationFood) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationFood.Unmarshal(m, b)
}
func (m *CreationFood) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationFood.Marshal(b, m, deterministic)
}
func (m *CreationFood) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationFood.Merge(m, src)
}
func (m *CreationFood) XXX_Size() int {
	return xxx_messageInfo_CreationFood.Size(m)
}
func (m *CreationFood) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationFood.DiscardUnknown(m)
}

var xxx_messageInfo_CreationFood proto.InternalMessageInfo

func (m *CreationFood) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreationFood) GetFoodT() FoodType {
	if m != nil {
		return m.FoodT
	}
	return FoodType_Unknown
}

func (m *CreationFood) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreationFood) GetPortionSize() float32 {
	if m != nil {
		return m.PortionSize
	}
	return 0
}

type Food struct {
	FoodId               uint64   `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FoodT                FoodType `protobuf:"varint,3,opt,name=food_t,json=foodT,proto3,enum=ova.food.api.FoodType" json:"food_t,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PortionSize          float32  `protobuf:"fixed32,5,opt,name=portion_size,json=portionSize,proto3" json:"portion_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{1}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetFoodId() uint64 {
	if m != nil {
		return m.FoodId
	}
	return 0
}

func (m *Food) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Food) GetFoodT() FoodType {
	if m != nil {
		return m.FoodT
	}
	return FoodType_Unknown
}

func (m *Food) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Food) GetPortionSize() float32 {
	if m != nil {
		return m.PortionSize
	}
	return 0
}

type CreateFoodV1Request struct {
	Food                 *CreationFood `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateFoodV1Request) Reset()         { *m = CreateFoodV1Request{} }
func (m *CreateFoodV1Request) String() string { return proto.CompactTextString(m) }
func (*CreateFoodV1Request) ProtoMessage()    {}
func (*CreateFoodV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{2}
}

func (m *CreateFoodV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFoodV1Request.Unmarshal(m, b)
}
func (m *CreateFoodV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFoodV1Request.Marshal(b, m, deterministic)
}
func (m *CreateFoodV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFoodV1Request.Merge(m, src)
}
func (m *CreateFoodV1Request) XXX_Size() int {
	return xxx_messageInfo_CreateFoodV1Request.Size(m)
}
func (m *CreateFoodV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFoodV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFoodV1Request proto.InternalMessageInfo

func (m *CreateFoodV1Request) GetFood() *CreationFood {
	if m != nil {
		return m.Food
	}
	return nil
}

type DescribeFoodV1Request struct {
	FoodId               uint64   `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeFoodV1Request) Reset()         { *m = DescribeFoodV1Request{} }
func (m *DescribeFoodV1Request) String() string { return proto.CompactTextString(m) }
func (*DescribeFoodV1Request) ProtoMessage()    {}
func (*DescribeFoodV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{3}
}

func (m *DescribeFoodV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeFoodV1Request.Unmarshal(m, b)
}
func (m *DescribeFoodV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeFoodV1Request.Marshal(b, m, deterministic)
}
func (m *DescribeFoodV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeFoodV1Request.Merge(m, src)
}
func (m *DescribeFoodV1Request) XXX_Size() int {
	return xxx_messageInfo_DescribeFoodV1Request.Size(m)
}
func (m *DescribeFoodV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeFoodV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeFoodV1Request proto.InternalMessageInfo

func (m *DescribeFoodV1Request) GetFoodId() uint64 {
	if m != nil {
		return m.FoodId
	}
	return 0
}

type DescribeFoodV1Response struct {
	Food                 *Food    `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeFoodV1Response) Reset()         { *m = DescribeFoodV1Response{} }
func (m *DescribeFoodV1Response) String() string { return proto.CompactTextString(m) }
func (*DescribeFoodV1Response) ProtoMessage()    {}
func (*DescribeFoodV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{4}
}

func (m *DescribeFoodV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeFoodV1Response.Unmarshal(m, b)
}
func (m *DescribeFoodV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeFoodV1Response.Marshal(b, m, deterministic)
}
func (m *DescribeFoodV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeFoodV1Response.Merge(m, src)
}
func (m *DescribeFoodV1Response) XXX_Size() int {
	return xxx_messageInfo_DescribeFoodV1Response.Size(m)
}
func (m *DescribeFoodV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeFoodV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeFoodV1Response proto.InternalMessageInfo

func (m *DescribeFoodV1Response) GetFood() *Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type ListFoodsV1Request struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFoodsV1Request) Reset()         { *m = ListFoodsV1Request{} }
func (m *ListFoodsV1Request) String() string { return proto.CompactTextString(m) }
func (*ListFoodsV1Request) ProtoMessage()    {}
func (*ListFoodsV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{5}
}

func (m *ListFoodsV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFoodsV1Request.Unmarshal(m, b)
}
func (m *ListFoodsV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFoodsV1Request.Marshal(b, m, deterministic)
}
func (m *ListFoodsV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFoodsV1Request.Merge(m, src)
}
func (m *ListFoodsV1Request) XXX_Size() int {
	return xxx_messageInfo_ListFoodsV1Request.Size(m)
}
func (m *ListFoodsV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFoodsV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_ListFoodsV1Request proto.InternalMessageInfo

func (m *ListFoodsV1Request) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListFoodsV1Response struct {
	Foods                map[uint64]*Food `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListFoodsV1Response) Reset()         { *m = ListFoodsV1Response{} }
func (m *ListFoodsV1Response) String() string { return proto.CompactTextString(m) }
func (*ListFoodsV1Response) ProtoMessage()    {}
func (*ListFoodsV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{6}
}

func (m *ListFoodsV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFoodsV1Response.Unmarshal(m, b)
}
func (m *ListFoodsV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFoodsV1Response.Marshal(b, m, deterministic)
}
func (m *ListFoodsV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFoodsV1Response.Merge(m, src)
}
func (m *ListFoodsV1Response) XXX_Size() int {
	return xxx_messageInfo_ListFoodsV1Response.Size(m)
}
func (m *ListFoodsV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFoodsV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_ListFoodsV1Response proto.InternalMessageInfo

func (m *ListFoodsV1Response) GetFoods() map[uint64]*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type RemoveFoodV1Request struct {
	FoodId               uint64   `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFoodV1Request) Reset()         { *m = RemoveFoodV1Request{} }
func (m *RemoveFoodV1Request) String() string { return proto.CompactTextString(m) }
func (*RemoveFoodV1Request) ProtoMessage()    {}
func (*RemoveFoodV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6704eb2a2c59a3d1, []int{7}
}

func (m *RemoveFoodV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFoodV1Request.Unmarshal(m, b)
}
func (m *RemoveFoodV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFoodV1Request.Marshal(b, m, deterministic)
}
func (m *RemoveFoodV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFoodV1Request.Merge(m, src)
}
func (m *RemoveFoodV1Request) XXX_Size() int {
	return xxx_messageInfo_RemoveFoodV1Request.Size(m)
}
func (m *RemoveFoodV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFoodV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFoodV1Request proto.InternalMessageInfo

func (m *RemoveFoodV1Request) GetFoodId() uint64 {
	if m != nil {
		return m.FoodId
	}
	return 0
}

func init() {
	proto.RegisterEnum("ova.food.api.FoodType", FoodType_name, FoodType_value)
	proto.RegisterType((*CreationFood)(nil), "ova.food.api.CreationFood")
	proto.RegisterType((*Food)(nil), "ova.food.api.Food")
	proto.RegisterType((*CreateFoodV1Request)(nil), "ova.food.api.CreateFoodV1Request")
	proto.RegisterType((*DescribeFoodV1Request)(nil), "ova.food.api.DescribeFoodV1Request")
	proto.RegisterType((*DescribeFoodV1Response)(nil), "ova.food.api.DescribeFoodV1Response")
	proto.RegisterType((*ListFoodsV1Request)(nil), "ova.food.api.ListFoodsV1Request")
	proto.RegisterType((*ListFoodsV1Response)(nil), "ova.food.api.ListFoodsV1Response")
	proto.RegisterMapType((map[uint64]*Food)(nil), "ova.food.api.ListFoodsV1Response.FoodsEntry")
	proto.RegisterType((*RemoveFoodV1Request)(nil), "ova.food.api.RemoveFoodV1Request")
}

func init() {
	proto.RegisterFile("api/ova-food-api/ova-food-api.proto", fileDescriptor_6704eb2a2c59a3d1)
}

var fileDescriptor_6704eb2a2c59a3d1 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xae, 0x9d, 0x9f, 0x36, 0x27, 0x51, 0x95, 0x4e, 0xd4, 0x36, 0x4a, 0xaf, 0xae, 0x5c, 0xb7,
	0xba, 0x72, 0xd3, 0x1b, 0x9b, 0x06, 0xa4, 0xfe, 0x80, 0x10, 0x35, 0x2d, 0x52, 0xa5, 0x4a, 0x95,
	0x42, 0x61, 0xd1, 0xaa, 0x8d, 0x26, 0xf5, 0x34, 0x8c, 0xd2, 0x78, 0x8c, 0xed, 0x18, 0x12, 0x84,
	0x84, 0xba, 0x64, 0x09, 0x0f, 0xc1, 0x33, 0xf0, 0x1c, 0xac, 0xd8, 0xf3, 0x06, 0xec, 0xb2, 0x42,
	0x33, 0x76, 0x48, 0x1c, 0x42, 0x2b, 0xb6, 0xec, 0x3c, 0xe7, 0x67, 0xbe, 0xef, 0x3b, 0xdf, 0xc9,
	0x04, 0x56, 0xb0, 0x43, 0x0d, 0x16, 0xe0, 0xca, 0x25, 0x63, 0x56, 0x65, 0xfc, 0xa0, 0x3b, 0x2e,
	0xf3, 0x19, 0xca, 0xb1, 0x00, 0xeb, 0x3c, 0xa6, 0x63, 0x87, 0x96, 0xfe, 0x69, 0x32, 0xd6, 0xbc,
	0x22, 0x06, 0x2f, 0xc6, 0xb6, 0xcd, 0x7c, 0xec, 0x53, 0x66, 0x7b, 0x61, 0x6d, 0x69, 0x29, 0xca,
	0x8a, 0x53, 0xa3, 0x73, 0x69, 0x90, 0xb6, 0xe3, 0x77, 0xa3, 0xe4, 0x62, 0x80, 0xaf, 0xa8, 0x85,
	0x7d, 0x62, 0x0c, 0x3e, 0xc2, 0x84, 0xfa, 0x55, 0x82, 0xdc, 0x63, 0x97, 0x88, 0x9b, 0x9e, 0x30,
	0x66, 0x21, 0x05, 0xa6, 0x3b, 0x1e, 0x71, 0xeb, 0xd4, 0x2a, 0xca, 0x8a, 0xa4, 0x25, 0xcd, 0xe9,
	0xbe, 0x99, 0xac, 0xca, 0xda, 0x54, 0x2d, 0xcd, 0xe3, 0x07, 0x16, 0xda, 0x84, 0x34, 0xa7, 0x54,
	0xf7, 0x8b, 0x09, 0x45, 0xd2, 0x66, 0xab, 0x0b, 0xfa, 0x28, 0x4b, 0x9d, 0xdf, 0x72, 0xdc, 0x75,
	0x88, 0x39, 0xd3, 0x37, 0x53, 0xd7, 0x92, 0x9c, 0x97, 0x6a, 0x29, 0x9e, 0x3c, 0x46, 0x26, 0x24,
	0x6d, 0xdc, 0x26, 0xc5, 0xa4, 0x22, 0x69, 0x19, 0x53, 0xef, 0x9b, 0xeb, 0xee, 0x9a, 0xf6, 0x4e,
	0xae, 0xae, 0x9e, 0x9f, 0x9e, 0x9f, 0xde, 0xa9, 0x6c, 0x9f, 0xed, 0x56, 0x4e, 0x70, 0xa5, 0x77,
	0xb6, 0xae, 0x29, 0x63, 0x81, 0xb5, 0xf2, 0x6a, 0x4d, 0xf4, 0xa2, 0x32, 0xe4, 0x1c, 0xe6, 0x72,
	0xb6, 0x75, 0x8f, 0xf6, 0x48, 0x31, 0xa5, 0x48, 0x9a, 0x3c, 0xe4, 0x98, 0x8d, 0x92, 0x4f, 0x69,
	0x8f, 0xa8, 0xdf, 0x25, 0x48, 0x0e, 0x34, 0x09, 0xc6, 0xd4, 0x2a, 0x4a, 0x63, 0x9a, 0x78, 0xfc,
	0xe0, 0xaf, 0x52, 0x7d, 0x04, 0x05, 0x61, 0x28, 0xe1, 0x94, 0x9e, 0x6f, 0xd4, 0xc8, 0xcb, 0x0e,
	0xf1, 0x7c, 0xb4, 0x05, 0x49, 0xce, 0x47, 0x0c, 0x20, 0x5b, 0x2d, 0xc5, 0xd9, 0x8f, 0x6e, 0x80,
	0x50, 0xf0, 0x5e, 0x28, 0x10, 0x1d, 0xea, 0x36, 0xcc, 0xef, 0x11, 0xef, 0xc2, 0xa5, 0x8d, 0xb1,
	0x2b, 0x6f, 0x1d, 0xab, 0xfa, 0x08, 0x16, 0xc6, 0x5b, 0x3d, 0x87, 0xd9, 0x1e, 0x41, 0xff, 0xc5,
	0xe8, 0xa0, 0x5f, 0x87, 0x19, 0x81, 0xdf, 0x03, 0x74, 0x48, 0x3d, 0x9f, 0x47, 0xbc, 0x21, 0xf2,
	0xbf, 0x90, 0xa0, 0x96, 0x57, 0x94, 0x94, 0x84, 0x96, 0x34, 0x73, 0x7d, 0x33, 0xf3, 0x41, 0x4a,
	0xab, 0x21, 0x34, 0x4f, 0xa8, 0x9f, 0x24, 0x28, 0xc4, 0xda, 0x22, 0x54, 0x13, 0x84, 0x29, 0x61,
	0x67, 0xb6, 0xfa, 0x7f, 0x1c, 0x76, 0x42, 0x87, 0xa0, 0xe2, 0xed, 0xdb, 0xbe, 0xdb, 0x0d, 0xfd,
	0xf4, 0x4a, 0x87, 0x00, 0xc3, 0x20, 0xca, 0x43, 0xa2, 0x45, 0xba, 0xa1, 0xfe, 0x1a, 0xff, 0x44,
	0x1a, 0xa4, 0x02, 0x7c, 0xd5, 0x21, 0x62, 0x91, 0x26, 0x4b, 0x0b, 0x0b, 0x76, 0xe4, 0x2d, 0x49,
	0xdd, 0x84, 0x42, 0x8d, 0xb4, 0x59, 0xf0, 0xa7, 0xa3, 0x2d, 0xeb, 0x30, 0x33, 0xd8, 0x39, 0x94,
	0x85, 0xe9, 0x67, 0x76, 0xcb, 0x66, 0xaf, 0xec, 0xfc, 0x14, 0x02, 0x48, 0xef, 0xb9, 0xd4, 0x6e,
	0x79, 0x79, 0x09, 0x65, 0x20, 0x25, 0xb8, 0xe6, 0xe5, 0xea, 0xe7, 0x04, 0xc0, 0x51, 0x80, 0xf9,
	0x71, 0xd7, 0xa1, 0xa8, 0x11, 0xfd, 0xec, 0x23, 0x5c, 0xb4, 0x3c, 0x61, 0x21, 0xe2, 0x9c, 0x4a,
	0x0b, 0x7a, 0xf8, 0xc2, 0xe8, 0x83, 0x17, 0x46, 0xdf, 0xe7, 0x2f, 0x8c, 0xba, 0x78, 0xfd, 0xe5,
	0xdb, 0x47, 0x79, 0x4e, 0xcd, 0x18, 0xc1, 0x86, 0x21, 0x66, 0xb4, 0x23, 0xbc, 0x43, 0xaf, 0x61,
	0x36, 0xee, 0x3e, 0x5a, 0x89, 0xa3, 0x4c, 0x5c, 0xab, 0xd2, 0xea, 0xcd, 0x45, 0xa1, 0x31, 0xea,
	0x92, 0x40, 0x9d, 0x47, 0x85, 0x9f, 0xa8, 0xc6, 0x9b, 0x68, 0x64, 0x6f, 0x11, 0x81, 0xec, 0x88,
	0x99, 0x48, 0xb9, 0xc1, 0xe7, 0x10, 0x73, 0xf9, 0xd6, 0x4d, 0x50, 0xe7, 0x04, 0x60, 0x16, 0x0d,
	0x65, 0xa2, 0x4b, 0xc8, 0x8d, 0x9a, 0x37, 0x3e, 0xc4, 0x09, 0xc6, 0xfe, 0x76, 0x88, 0x91, 0x9c,
	0xf2, 0x24, 0x39, 0xe6, 0xc3, 0x93, 0x07, 0x4d, 0xea, 0xbf, 0xe8, 0x34, 0xf4, 0x0b, 0xd6, 0x36,
	0x58, 0x8f, 0xd9, 0x01, 0x8e, 0xff, 0x77, 0x38, 0xad, 0x66, 0x2c, 0x70, 0x9f, 0x05, 0xb8, 0x2e,
	0xfa, 0xb1, 0x43, 0x1b, 0x69, 0x01, 0x76, 0xf7, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xd6,
	0xe3, 0x52, 0x74, 0x06, 0x00, 0x00,
}
