name: build-test

on:
  pull_request:
    branches: [ main ]

jobs:

  buil-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Deps
      run: make install-deps
      
    - name: Build
      run: make build

    - name: Test
      run: make test
